import type { Metadata } from "next";
import { ThemeProviderWrapper } from "@components/ThemeProviderWrapper";
import Header from "@components/Header";
import Footer from "@components/Footer";
import StyledComponentsRegistry from "@components/StyledComponentsRegistry";

export const metadata: Metadata = {
  title: "Andrea Dayo | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeProviderWrapper>
            <Header />
            {children}
            <Footer />
          </ThemeProviderWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
