import type { Metadata } from "next";
import { ThemeProviderWrapper } from "@components/ThemeProviderWrapper";
import AppContent from "@components/AppContent";
import StyledComponentsRegistry from "@components/StyledComponentsRegistry";
import { getSingleton } from "@/src/sanity/lib/singleton";

export const metadata: Metadata = {
  title: "Andrea Dayo | Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = await getSingleton("navLinks");

  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeProviderWrapper>
            <AppContent nav={navLinks}>{children}</AppContent>
          </ThemeProviderWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
